# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ""

setup(
    long_description=readme,
    name="csgo-quake-sounds",
    version="1.5.0",
    description="Play quake sounds via Gamestate Integration",
    python_requires="==3.*,>=3.7.0",
    author="kiwec",
    license="UNLICENSE",
    packages=[],
    package_dir={"": "."},
    package_data={},
    install_requires=[
        "aiofiles==0.*,>=0.4.0",
        "packel==1.*,>=1.0.0",
        "pyogg==0.6.11a1",
        "pyopenal==0.7.9a1",
        "steamfiles",
        "wxasync==0.*,>=0.41.0",
    ],
    dependency_links=["git+https://github.com/leovp/steamfiles.git#egg=steamfiles"],
)
